version: '3.7'
services:
    server:
        container_name: server
        build:
            context: ./
            dockerfile: ./docker/server.dockerfile
        volumes:
            - './server:/app'
            - '/app/node_modules'
        ports:
            - 3000:3000
        environment:
            "PORT": 3000
        stdin_open: true
        tty: true

    webapp:
        container_name: webapp
        build:
            context: ./
            dockerfile: ./docker/web.dockerfile
        volumes:
            - './webapp:/app'
            - '/app/node_modules'
        ports:
            - 3001:3001
        environment:
            - CHOKIDAR_USEPOLLING=true
            - PORT=3001
        stdin_open: true
        tty: true