version: '3.7'
services:
    server:
        container_name: server
        build:
            context: ./
            dockerfile: ./docker/server.dockerfile
        volumes:
            - './server:/app'
            - '/app/node_modules'
        ports:
            - 3000:3000
        environment:
            PORT: 3000
            MONGO_PORT: 27017
            MONGO_USER: "root"
            MONGO_PW: "password"
            MONGO_HOST: 'mongo'
            DATABASE_NAME: "expiration"
        stdin_open: true
        tty: true

    mongo:
        container_name: mongo
        build:
            context: ./
            dockerfile: ./docker/db.dockerfile
        volumes:
            - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
            - ./db/storage:/data/db
        restart: always
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_DATABASE: expiration
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password

    webapp:
        container_name: webapp
        build:
            context: ./
            dockerfile: ./docker/web.dockerfile
        volumes:
            - './webapp:/app'
            - '/app/node_modules'
        ports:
            - 3001:3001
        environment:
            - CHOKIDAR_USEPOLLING=true
            - PORT=3001
        stdin_open: true
        tty: true
