export const APIPaths = {
    expirable: '/api/expirable'
}

export const ACTIONS = {
    FETCH_EXPIRABLES: 'FETCH_EXPIRATION_ITEMS',
    FETCH_EXPIRABLES_COMPLETE: 'FETCH_EXPIRATION_ITEMS_COMPLETE',
    SAVE_EXPIRABLE: 'SAVE_EXPIRABLE',
    SAVE_EXPIRABLE_COMPLETE: 'SAVE_EXPIRABLE_COMPLETE',
}
